/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/cp/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/cp/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/cp/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/cp/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/cp/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/cp/AppTopbar.vue')['default']
    Chart: typeof import('chart.js')['Chart']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
